export const archeryCategoryMap: Record<string, string> = {
  "MM": "50+ Men Team",
  "MMT": "50+ Men Team",
  "W1MM": "50+ Men W1 (Rec/Comp)",
  "MW": "50+ Women Team",
  "MWT": "50+ Women Team",
  "W1MW": "50+ Women W1 (Rec/Comp)",
  "AL35JM": "American Longbow 35 Lbs (15.88kg) Junior Men",
  "AL35JW": "American Longbow 35 Lbs (15.88kg) Junior Women",
  "AL35M": "American Longbow 35 Lbs (15.88kg) Men",
  "AL35W": "American Longbow 35 Lbs (15.88kg) Women",
  "AL50JM": "American Longbow 50 Lbs (22.7kg) Junior Men",
  "AL50JW": "American Longbow 50 Lbs (22.7kg) Junior Women",
  "AL50M": "American Longbow 50 Lbs (22.7kg) Men",
  "AL50W": "American Longbow 50 Lbs (22.7kg) Women",
  "ALUJM": "American Longbow Unlimited Junior Men",
  "ALUJW": "American Longbow Unlimited Junior Women",
  "ALUM": "American Longbow Unlimited Men",
  "ALUW": "American Longbow Unlimited Women",
  "BMM": "Barebow 50+ Men",
  "BMX": "Barebow 50+ Mixed Team",
  "BMXT": "Barebow 50+ Mixed Team",
  "BMW": "Barebow 50+ Women",
  "B5M": "Barebow Master Men (50-59 years)",
  "B6M": "Barebow Master Men (60-69 years)",
  "B7M": "Barebow Master Men (70 years and over)",
  "B5W": "Barebow Master Women (50-59 years)",
  "B6W": "Barebow Master Women (60-69 years)",
  "B7W": "Barebow Master Women (70 years and over)",
  "BM": "Barebow Men",
  "B4M": "Barebow Men (49 years or less)",
  "BX": "Barebow Mixed Team",
  "BXT": "Barebow Mixed Team",
  "BU15M": "Barebow Under 15 Men",
  "BU15X": "Barebow Under 15 Mixed Team",
  "BU15XT": "Barebow Under 15 Mixed Team",
  "BU15W": "Barebow Under 15 Women",
  "BCM": "Barebow Under 18 Men",
  "BCX": "Barebow Under 18 Mixed Team",
  "BCXT": "Barebow Under 18 Mixed Team",
  "BCW": "Barebow Under 18 Women",
  "BJM": "Barebow Under 21 Men",
  "BJX": "Barebow Under 21 Mixed Team",
  "BJXT": "Barebow Under 21 Mixed Team",
  "BJW": "Barebow Under 21 Women",
  "BW": "Barebow Women",
  "B4W": "Barebow Women (49 years or less)",
  "C": "Compound",
  "CMM": "Compound 50+ Men",
  "CMMO": "Compound 50+ Men Open",
  "CMX": "Compound 50+ Mixed Team",
  "CMXT": "Compound 50+ Mixed Team",
  "CMW": "Compound 50+ Women",
  "CMWO": "Compound 50+ Women Open",
  "CF39JM": "Compound Flight Bow 39.7 Lbs (18kg) Junior Men",
  "CF39JW": "Compound Flight Bow 39.7 Lbs (18kg) Junior Women",
  "CF39W": "Compound Flight Bow 39.7 Lbs (18kg) Women",
  "CF55JM": "Compound Flight Bow 55.1 Lbs (25kg) Junior Men",
  "CF55JW": "Compound Flight Bow 55.1 Lbs (25kg) Junior Women",
  "CF55M": "Compound Flight Bow 55.1 Lbs (25kg) Men",
  "CF55W": "Compound Flight Bow 55.1 Lbs (25kg) Women",
  "CF72M": "Compound Flight Bow 72.8 Lbs (33kg) Men",
  "CFUJM": "Compound Flight Bow Unlimited Junior Men",
  "CFUJW": "Compound Flight Bow Unlimited Junior Women",
  "CFUM": "Compound Flight Bow Unlimited Men",
  "CFUW": "Compound Flight Bow Unlimited Women",
  "C5M": "Compound Master Men (50-59 years)",
  "C6M": "Compound Master Men (60-69 years)",
  "C7M": "Compound Master Men (70 years and over)",
  "C5W": "Compound Master Women (50-59 years)",
  "C6W": "Compound Master Women (60-69 years)",
  "C7W": "Compound Master Women (70 years and over)",
  "CM": "Compound Men",
  "C4M": "Compound Men (49 years or less)",
  "CMO": "Compound Men Open",
  "CMOT": "Compound Men Open Team",
  "CMW1": "Compound Men W1",
  "CX": "Compound Mixed Team",
  "CXT": "Compound Mixed Team",
  "CXO": "Compound Mixed Team Open",
  "CXOT": "Compound Mixed Team Open",
  "CT45JM": "Compound Target Bow 45 Lbs (20.4kg) Junior Men",
  "CT45JW": "Compound Target Bow 45 Lbs (20.4kg) Junior Women",
  "CT45M": "Compound Target Bow 45 Lbs (20.4kg) Men",
  "CT45W": "Compound Target Bow 45 Lbs (20.4kg) Women",
  "CT60JM": "Compound Target Bow 60 Lbs (27.2kg) Junior Men",
  "CT60JW": "Compound Target Bow 60 Lbs (27.2kg) Junior Women",
  "CT60M": "Compound Target Bow 60 Lbs (27.2kg) Men",
  "CT60W": "Compound Target Bow 60 Lbs (27.2kg) Women",
  "CT": "Compound Team",
  "CTT": "Compound Team",
  "CU15M": "Compound Under 15 Men",
  "CU15X": "Compound Under 15 Mixed Team",
  "CU15XT": "Compound Under 15 Mixed Team",
  "CU15W": "Compound Under 15 Women",
  "CCM": "Compound Under 18 Men",
  "CCMT": "Compound Under 18 Men Team",
  "CCMO": "Compound Under 18 Men Open",
  "CCX": "Compound Under 18 Mixed Team",
  "CCXT": "Compound Under 18 Mixed Team",
  "CCW": "Compound Under 18 Women",
  "CCWT": "Compound Under 18 Women Team",
  "CCWO": "Compound Under 18 Women Open",
  "CJM": "Compound Under 21 Men",
  "CJMT": "Compound Under 21 Men Team",
  "CJMO": "Compound Under 21 Men Open",
  "CJX": "Compound Under 21 Mixed Team",
  "CJXT": "Compound Under 21 Mixed Team",
  "CJW": "Compound Under 21 Women",
  "CJWT": "Compound Under 21 Women Team",
  "CJWO": "Compound Under 21 Women Open",
  "CW": "Compound Women",
  "C4W": "Compound Women (49 years or less)",
  "CWO": "Compound Women Open",
  "CWOT": "Compound Women Open Team",
  "CWW1": "Compound Women W1",
  "FC39JM": "Conventional Flight Bow 39.7 Lbs (18kg) Junior Men",
  "FC39JW": "Conventional Flight Bow 39.7 Lbs (18kg) Junior Women",
  "FC39M": "Conventional Flight Bow 39.7 Lbs (18kg) Men",
  "FC39W": "Conventional Flight Bow 39.7 Lbs (18kg) Women",
  "FC55JM": "Conventional Flight Bow 55.1 Lbs (25kg) Junior Men",
  "FC55JW": "Conventional Flight Bow 55.1 Lbs (25kg) Junior Women",
  "FC55M": "Conventional Flight Bow 55.1 Lbs (25kg) Men",
  "FC55W": "Conventional Flight Bow 55.1 Lbs (25kg) Women",
  "FC72JM": "Conventional Flight Bow 72.8 Lbs (33kg) Junior Men",
  "FC72JW": "Conventional Flight Bow 72.8 Lbs (33kg) Junior Women",
  "FC72M": "Conventional Flight Bow 72.8 Lbs (33kg) Men",
  "FC72W": "Conventional Flight Bow 72.8 Lbs (33kg) Women",
  "FCUJM": "Conventional Flight Bow Unlimited Junior Men",
  "FCUJW": "Conventional Flight Bow Unlimited Junior Women",
  "FCUM": "Conventional Flight Bow Unlimited Men",
  "FCUW": "Conventional Flight Bow Unlimited Women",
  "EL35JM": "English Longbow 35 Lbs (15.88kg) Junior Men",
  "EL35JW": "English Longbow 35 Lbs (15.88kg) Junior Women",
  "EL35M": "English Longbow 35 Lbs (15.88kg) Men",
  "EL35W": "English Longbow 35 Lbs (15.88kg) Women",
  "EL50JM": "English Longbow 50 Lbs (22.7kg) Junior Men",
  "EL50JW": "English Longbow 50 Lbs (22.7kg) Junior Women",
  "EL50M": "English Longbow 50 Lbs (22.7kg) Men",
  "EL50W": "English Longbow 50 Lbs (22.7kg) Women",
  "ELUJM": "English Longbow Unlimited Junior Men",
  "ELUJW": "English Longbow Unlimited Junior Women",
  "ELUM": "English Longbow Unlimited Men",
  "ELUW": "English Longbow Unlimited Women",
  "FBUJM": "Foot Bow Unlimited Junior Men",
  "FBUJW": "Foot Bow Unlimited Junior Women",
  "FBUM": "Foot Bow Unlimited Men",
  "FBUW": "Foot Bow Unlimited Women",
  "IM": "Instinctive bow Men",
  "IX": "Instinctive bow Mixed Team",
  "IXT": "Instinctive bow Mixed Team",
  "IW": "Instinctive bow Women",
  "I5M": "Instinctive Master Men (50-59 years)",
  "I6M": "Instinctive Master Men (60-69 years)",
  "I7M": "Instinctive Master Men (70 years and over)",
  "I5W": "Instinctive Master Women (50-59 years)",
  "I6W": "Instinctive Master Women (60-69 years)",
  "I7W": "Instinctive Master Women (70 years and over)",
  "I4M": "Instinctive Men (49 years or less)",
  "I4W": "Instinctive Women (49 years or less)",
  "L5M": "Longbow Master Men (50-59 years)",
  "L6M": "Longbow Master Men (60-69 years)",
  "L7M": "Longbow Master Men (70 years and over)",
  "L5W": "Longbow Master Women (50-59 years)",
  "L6W": "Longbow Master Women (60-69 years)",
  "L7W": "Longbow Master Women (70 years and over)",
  "LM": "Longbow Men",
  "L4M": "Longbow Men (49 years or less)",
  "LX": "Longbow Mixed Team",
  "LXT": "Longbow Mixed Team",
  "LW": "Longbow Women",
  "L4W": "Longbow Women (49 years or less)",
  "M": "Men Team",
  "MT": "Men Team",
  "MW1": "Men W1 (Rec/Comp)",
  "MW1T": "Men W1 (Rec/Comp) Team",
  "W1X": "Mixed Team W1 (Rec/Comp)",
  "W1XT": "Mixed Team W1 (Rec/Comp)",
  "R": "Recurve",
  "RMM": "Recurve 50+ Men",
  "RMMO": "Recurve 50+ Men Open",
  "RMX": "Recurve 50+ Mixed Team",
  "RMXT": "Recurve 50+ Mixed Team",
  "RMW": "Recurve 50+ Women",
  "RMWO": "Recurve 50+ Women Open",
  "R5M": "Recurve Master Men (50-59 years)",
  "R6M": "Recurve Master Men (60-69 years)",
  "R7M": "Recurve Master Men (70 years and over)",
  "R5W": "Recurve Master Women (50-59 years)",
  "R6W": "Recurve Master Women (60-69 years)",
  "R7W": "Recurve Master Women (70 years and over)",
  "RM": "Recurve Men",
  "R4M": "Recurve Men (49 years or less)",
  "RMO": "Recurve Men Open",
  "RMOT": "Recurve Men Open Team",
  "RMOp": "Recurve Men Open",
  "RMSt": "Recurve Men Standing",
  "RMW1": "Recurve Men W1",
  "RMW2": "Recurve Men W2",
  "RX": "Recurve Mixed Team",
  "RXT": "Recurve Mixed Team",
  "RXO": "Recurve Mixed Team Open",
  "RXOT": "Recurve Mixed Team Open",
  "RT": "Recurve Team",
  "RTT": "Recurve Team",
  "RU15M": "Recurve Under 15 Men",
  "RU15X": "Recurve Under 15 Mixed Team",
  "RU15XT": "Recurve Under 15 Mixed Team",
  "RU15W": "Recurve Under 15 Women",
  "RCM": "Recurve Under 18 Men",
  "RCMT": "Recurve Under 18 Men Team",
  "RCMO": "Recurve Under 18 Men Open",
  "RCX": "Recurve Under 18 Mixed Team",
  "RCXT": "Recurve Under 18 Mixed Team",
  "RCW": "Recurve Under 18 Women",
  "RCWT": "Recurve Under 18 Women Team",
  "RCWO": "Recurve Under 18 Women Open",
  "RJM": "Recurve Under 21 Men",
  "RJMO": "Recurve Under 21 Men Open",
  "RJX": "Recurve Under 21 Mixed Team",
  "RJXT": "Recurve Under 21 Mixed Team",
  "RJW": "Recurve Under 21 Women",
  "RJWT": "Recurve Under 21 Women Team",
  "RJMT": "Recurve Under 21 Men Team",
  "RJWO": "Recurve Under 21 Women Open",
  "RW": "Recurve Women",
  "R4W": "Recurve Women (49 years or less)",
  "RWO": "Recurve Women Open",
  "RWOT": "Recurve Women Open Team",
  "RWOp": "Recurve Women Open",
  "RWSt": "Recurve Women Standing",
  "RWW2": "Recurve Women W2",
  "RT35JM": "Target Recurve Bow 35 Lbs (15.88kg) Junior Men",
  "RT35JW": "Target Recurve Bow 35 Lbs (15.88kg) Junior Women",
  "RT35M": "Target Recurve Bow 35 Lbs (15.88kg) Men",
  "RT35W": "Target Recurve Bow 35 Lbs (15.88kg) Women",
  "RT50JM": "Target Recurve Bow 50 Lbs (22.7kg) Junior Men",
  "RT50JW": "Target Recurve Bow 50 Lbs (22.7kg) Junior Women",
  "RT50M": "Target Recurve Bow 50 Lbs (22.7kg) Men",
  "RT50W": "Target Recurve Bow 50 Lbs (22.7kg) Women",
  "TM": "Traditional bow Men",
  "TX": "Traditional bow Mixed Team",
  "TXT": "Traditional bow Mixed Team",
  "TW": "Traditional bow Women",
  "CMT": "Under 18 Men Team",
  "CMTT": "Under 18 Men Team",
  "W1CM": "Under 18 Men W1 (Rec/Comp)",
  "CWT": "Under 18 Women Team",
  "CWTT": "Under 18 Women Team",
  "W1CW": "Under 18 Women W1 (Rec/Comp)",
  "JM": "Under 21 Men Team",
  "JMT": "Under 21 Men Team",
  "W1JM": "Under 21 Men W1 (Rec/Comp)",
  "JW": "Under 21 Women Team",
  "JWT": "Under 21 Women Team",
  "W1JW": "Under 21 Women W1 (Rec/Comp)",
  "VIM": "Visual Impaired Men",
  "VIW": "Visual Impaired Women",
  "VI1": "Visually Impaired 1",
  "VI23": "Visually Impaired 2 / 3",
  "W": "Women Team",
  "WT": "Women Team",
  "WW1": "Women W1 (Rec/Comp)"
};